---
spring:
  profiles: default
  datasource:
    url: "jdbc:sqlite:C:/Users/sgonzmot/git/proyectosJava/ZooDeSanti/sqlite.db"
    driver-class-name: org.sqlite.JDBC
    initialization-mode: never
    hikari:
      maximum-pool-size: 1
---
spring:
  profiles: cloud